# Generated by Django 2.2.2 on 2019-07-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('hobby', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('hobby', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('riko_description', models.CharField(max_length=500)),
                ('spice_level', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='meal_images/')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=500)),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Cooking'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('hobby', models.CharField(max_length=500)),
                ('anime', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='registration_logo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaytmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TXNID', models.CharField(max_length=70, verbose_name='TNX ID')),
                ('BANKTXNID', models.CharField(blank=True, max_length=60, null=True, verbose_name='BANK TXN ID')),
                ('ORDERID', models.CharField(max_length=70, verbose_name='ORDER ID')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('STATUS', models.CharField(max_length=30, verbose_name='STATUS')),
                ('TXNTYPE', models.CharField(blank=True, max_length=10, null=True, verbose_name='TNX TYPE')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=20, null=True, verbose_name='GATEWAY NAME')),
                ('RESPCODE', models.CharField(max_length=20, verbose_name='STATUS')),
                ('RESPMSG', models.TextField(max_length=600, verbose_name='RESP MSG')),
                ('BANKNAME', models.CharField(blank=True, max_length=600, null=True, verbose_name='BANK NAME')),
                ('MID', models.CharField(max_length=40)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAYMENT MODE')),
                ('REFUNDAMT', models.FloatField(default=0, verbose_name='RFUND AMOUNT')),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='deploytodotaskerapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='deploytodotaskerapp.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Registration'),
        ),
        migrations.AddField(
            model_name='meal',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Registration'),
        ),
    ]
