# Generated by Django 2.2.2 on 2019-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
