# Generated by Django 2.2.2 on 2019-07-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal Simple Verbose', 'verbose_name_plural': 'Meal Plural Verbose'},
        ),
    ]
