# Generated by Django 2.1.7 on 2019-06-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0014_paytmhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='paytmhistory',
            name='TXNTYPE',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TNX TYPE'),
        ),
    ]
