# Generated by Django 2.1.7 on 2019-06-29 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0017_auto_20190629_1817'),
    ]

    operations = [
 
        migrations.AddField(
            model_name='paytmhistory',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='deploytodotaskerapp.Order'),
            preserve_default=False,
        )

    ]
