# Generated by Django 2.2.2 on 2019-06-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0018_auto_20190629_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmhistory',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='deploytodotaskerapp.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=70, verbose_name='TNX ID'),
        ),
    ]
