# Generated by Django 2.2.2 on 2019-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0020_auto_20190709_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='anime',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
