# Generated by Django 2.2.2 on 2019-07-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0021_registration_anime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='short_description',
            new_name='riko_description',
        ),
    ]
