# Generated by Django 2.2.2 on 2019-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0022_auto_20190709_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='spice_level',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
