# Generated by Django 2.2.2 on 2019-07-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploytodotaskerapp', '0023_meal_spice_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='hobby',
        ),
    ]
